# Generated by Django 3.1.5 on 2021-01-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjezba8app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upisi',
            name='predmet_id',
        ),
        migrations.RemoveField(
            model_name='upisi',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Korisnik',
        ),
        migrations.DeleteModel(
            name='Upisi',
        ),
    ]
