# Generated by Django 3.1.5 on 2021-01-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjezba8app', '0003_korisnik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
