# Generated by Django 3.1.5 on 2021-01-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vjezba8app', '0004_delete_korisnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('mentor', 'mentor'), ('student', 'student')], max_length=50)),
                ('status', models.CharField(choices=[('none', 'none'), ('redovni', 'redovni'), ('izvanredni', 'izvanredni')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
